const flashcards = [
  // ===== SESSION 1: Intro (3) =====
  { s:1, q: "What is Consumer Behaviour?", a: "The processes involved when individuals or groups SELECT, PURCHASE, USE, or DISPOSE of products, services, ideas, or experiences to SATISFY NEEDS AND DESIRES." },
  { s:1, q: "What is a Market Study?", a: "The SYSTEMATIC and OBJECTIVE identification, collection, analysis, dissemination, and use of INFORMATION for IMPROVING DECISION MAKING related to marketing problems and opportunities." },
  { s:1, q: "3 Roles of a Market Study?", a: "1) ASSESSING information needs, 2) PROVIDING relevant information, 3) Helping management make INFORMED DECISIONS. It reduces uncertainty with factual data." },
  // ===== SESSION 2: Attitude, Behaviour, Belief (12) =====
  { s:2, q: "Behaviour = ?", a: "What a consumer DOES. OBSERVED and FACTUAL. You can see it.\nEx: 'I buy organic food every week.'" },
  { s:2, q: "Attitude = ?", a: "What a consumer THINKS or FEELS. CANNOT be directly observed. An overall EVALUATION (positive or negative).\nEx: 'I think organic food is healthier.'" },
  { s:2, q: "Belief = ?", a: "The COGNITIVE INFORMATION a consumer holds about an attitude object. What the consumer KNOWS or thinks they know.\nEx: 'Organic food contains no pesticides.'" },
  { s:2, q: "Quick distinction: Behaviour vs Attitude vs Belief?", a: "BEHAVIOUR = ACTION (observable)\nATTITUDE = EVALUATION (feeling/thinking, not observable)\nBELIEF = KNOWLEDGE (cognitive info, resistant to change)" },
  { s:2, q: "The Consumer's Black Box contains?", a: "2 components:\n1) CONSUMER CHARACTERISTICS (personal, psychological, socio-cultural)\n2) DECISION PROCESS\nInputs = environment stimuli | Outputs = consumer responses" },
  { s:2, q: "Consumer Behaviour Model flow?", a: "ENVIRONMENT (marketing stimuli + other stimuli) -> CONSUMER'S BLACK BOX (characteristics + decision process) -> CONSUMER RESPONSES (attitudes, purchase behaviour...)" },
  { s:2, q: "3 Components of Attitude (ABC Model)?", a: "A = AFFECT (what you feel)\nB = BEHAVIOUR/Conation (intention to act)\nC = COGNITION (what you know/believe)" },
  { s:2, q: "3 Ways Attitudes Form?", a: "1) DIRECT EXPERIENCE (personal interaction -> stronger attitudes)\n2) CLASSICAL CONDITIONING (pairing neutral + natural stimulus)\n3) OPERANT CONDITIONING (rewards/punishments shape attitudes)" },
  { s:2, q: "Classical vs Operant Conditioning?", a: "CLASSICAL: neutral stimulus paired with one that naturally triggers response (e.g., music + brand)\nOPERANT: attitude shaped by REWARDS and PUNISHMENTS" },
  { s:2, q: "3 Types of Consumer Characteristics?", a: "1) PERSONAL (age, lifestyle, personality)\n2) PSYCHOLOGICAL (motivation, perception, learning, attitude)\n3) SOCIO-CULTURAL (culture, social class, family)" },
  { s:2, q: "Key Properties of Beliefs?", a: "- RESISTANT to change\n- Can be POSITIVE, NEUTRAL, or NEGATIVE\n- Represent cognitive knowledge\n- Inform attitudes" },
  { s:2, q: "How to distinguish Attitude from Belief in an MCQ?", a: "ATTITUDE = overall evaluation (like/dislike, good/bad)\nBELIEF = factual claim (true/false knowledge)\nEx: 'Organic is healthier' = ATTITUDE | 'Organic has no pesticides' = BELIEF" },
  // ===== SESSION 3: Perception, Motivation, Emotion (15) =====
  { s:3, q: "Perception = ?", a: "The process by which sensory information is SELECTED, ORGANIZED, and INTERPRETED. How people make sense of the world." },
  { s:3, q: "Sensation = ?", a: "The IMMEDIATE RESPONSE of sensory receptors (eyes, ears, nose, mouth, skin) to basic stimuli (light, colour, sound, odour, texture)." },
  { s:3, q: "Perception vs Sensation?", a: "SENSATION = raw, immediate sensory response (input)\nPERCEPTION = selecting + organizing + interpreting that input (processing)" },
  { s:3, q: "Perceptual Process (Solomon, 2018)?", a: "Sensory stimuli -> Sensory receptors -> EXPOSURE -> ATTENTION -> INTERPRETATION\n(5 stages, in this exact order)" },
  { s:3, q: "Functional vs Symbolic Attributes?", a: "FUNCTIONAL = tangible, measurable (taste, price, weight, smell)\nSYMBOLIC = intangible (brand image, perceived quality, status, authenticity)" },
  { s:3, q: "Absolute Threshold vs Differential Threshold (JND)?", a: "ABSOLUTE = minimum stimulation DETECTED on a sensory channel\nDIFFERENTIAL (JND) = ability to detect CHANGES or DIFFERENCES between two stimuli" },
  { s:3, q: "What is Subliminal Perception?", a: "Stimuli BELOW the absolute threshold. Consumer is NOT consciously aware but behaviour may still be influenced." },
  { s:3, q: "Perceptual Vigilance vs Perceptual Defence?", a: "VIGILANCE = notice stimuli related to CURRENT NEEDS\nDEFENCE = BLOCK threatening or unpleasant stimuli (see what you want to see)" },
  { s:3, q: "Sensory Overload?", a: "Exposed to FAR MORE INFORMATION than can be processed. Common in multitasking environments." },
  { s:3, q: "Motivation = ?", a: "The process that leads people to BEHAVE AS THEY DO. Occurs when a NEED IS AROUSED that the consumer wishes to satisfy, creating TENSION that drives action." },
  { s:3, q: "Maslow's Hierarchy (5 levels)?", a: "Bottom to top:\n1) PHYSIOLOGICAL (food, water)\n2) SAFETY (security)\n3) BELONGINGNESS/Love\n4) ESTEEM (status, recognition)\n5) SELF-ACTUALIZATION" },
  { s:3, q: "3 Motivational Conflicts?", a: "1) APPROACH-APPROACH = 2 desirable options\n2) APPROACH-AVOIDANCE = product has + AND - qualities\n3) AVOIDANCE-AVOIDANCE = 2 undesirable options" },
  { s:3, q: "Approach-Avoidance conflict example?", a: "Wanting a chocolate cake (approach) but worrying about calories (avoidance). The product has BOTH positive and negative qualities." },
  { s:3, q: "Moods vs Emotions?", a: "MOODS = mild, diffuse, NO clear cause, last LONGER\nEMOTIONS = intense, specific, CLEAR CAUSE, SHORT-LIVED" },
  { s:3, q: "What is Affect?", a: "UMBRELLA TERM for moods + emotions. The experience of emotionally laden states." },
  // ===== SESSION 4: Market Study Phases (8) =====
  { s:4, q: "5 Stages of a Market Study?", a: "1. FORMULATE the problem\n2. DETERMINE study design\n3. DATA COLLECTION & sampling\n4. ANALYZE & interpret\n5. REPORT & delivery\n-> Make DECISIONS" },
  { s:4, q: "MDP vs MSP?", a: "MDP = what the decision maker needs to DO (ACTION-oriented, focuses on SYMPTOMS)\nMSP = what INFORMATION is needed (RESEARCH-oriented, focuses on UNDERLYING CAUSES)" },
  { s:4, q: "MDP example vs MSP example?", a: "MDP: 'Should Starbucks launch a drive-thru in France?'\nMSP: 'What are consumers beliefs, perceptions, motivations towards a drive-thru?'" },
  { s:4, q: "Brief vs Proposal?", a: "BRIEF = from the CLIENT (background, objectives, scope, budget, timing)\nPROPOSAL = from the SUPPLIER/RESEARCH INSTITUTE (methodology, sample, timeline, budget, ethics)" },
  { s:4, q: "Exploratory vs Conclusive Study?", a: "EXPLORATORY = insights, understanding, flexible, unstructured, small sample, qualitative\nCONCLUSIVE = test hypotheses, examine relationships, structured, large sample, quantitative" },
  { s:4, q: "Descriptive Study = ?", a: "Type of CONCLUSIVE study. DESCRIBES market characteristics: user profiles, percentages of behaviours, triggers. It is EXPLANATORY." },
  { s:4, q: "Causal Study = ?", a: "Type of CONCLUSIVE study. Evidence of CAUSE-AND-EFFECT relationships. Does X (cause) influence Y (effect)? It is CONFIRMATORY." },
  { s:4, q: "3 Study Design Types and their purpose?", a: "1) EXPLORATORY (qualitative) = understand, explore\n2) DESCRIPTIVE (quantitative) = describe, measure, explain\n3) CAUSAL (quantitative) = confirm cause-effect relationships" },
  // ===== SESSION 5: Secondary Data (5) =====
  { s:5, q: "Primary vs Secondary Data?", a: "PRIMARY = collected FOR this study (expensive, slow, very involved)\nSECONDARY = already EXISTS, collected for other purposes (cheap, fast, prerequisite)" },
  { s:5, q: "Key rule about Secondary Data?", a: "Examination of secondary data is a PREREQUISITE to primary data collection. A market study ALWAYS starts with secondary data." },
  { s:5, q: "Internal vs External Secondary Data?", a: "INTERNAL = within organization (client database, CRM/ERP, internal reports)\nEXTERNAL = outside (government/census, professional associations, press, social media, syndicated services)" },
  { s:5, q: "3 Sieves of Socrates?", a: "For evaluating secondary data:\n1) Is it TRUE?\n2) Is it GOOD?\n3) Is it USEFUL?\nAlso check: methodology, accuracy, currency, content, purpose, credibility." },
  { s:5, q: "Uses of Secondary Data?", a: "Identify the problem, better define it, develop approach, formulate research design, answer study questions, interpret primary data more insightfully." },
  // ===== SESSION 6: Qualitative Study (10) =====
  { s:6, q: "Qualitative Study = ?", a: "UNSTRUCTURED, EXPLORATORY methodology. SMALL samples. Provides INSIGHT and UNDERSTANDING. Focus on WORDS, concepts, ideas, opinions. Data is NON-NUMERICAL." },
  { s:6, q: "Qualitative Study Procedures?", a: "DIRECT (nondisguised): Focus Groups, Depth Interviews\nINDIRECT (disguised): Projective Techniques" },
  { s:6, q: "Advantages of Qualitative Study?", a: "- Deeper insights than secondary data\n- Uncover UNDERLYING REASONS\n- Probe for motivations\n- Free exchange of information\n- Attribute responses to respondents" },
  { s:6, q: "Disadvantages of Qualitative Study?", a: "- Skilled interviewers are EXPENSIVE\n- SMALL sample = not conclusive\n- Quality depends on INTERVIEWER" },
  { s:6, q: "Depth Interview = ?", a: "DIRECT, PERSONAL, ONE-TO-ONE interview. Skilled interviewer probes for underlying opinions, motivations, beliefs, attitudes, feelings. Duration: 30 min to 1 hour." },
  { s:6, q: "Saturation Effect = ?", a: "When NO NEW insights, ideas, or patterns emerge as you interview more participants. Signals the END of interviews. Sample size CANNOT be known beforehand." },
  { s:6, q: "3 Interview Techniques?", a: "1) STRUCTURED = fixed questions, fixed order\n2) SEMI-STRUCTURED = set topics, FLEXIBLE order, follow-ups allowed\n3) NARRATIVE = open-ended, respondent tells story" },
  { s:6, q: "Interview Guide (4 phases)?", a: "1) INTRODUCTORY (build trust, explain purpose)\n2) SUBJECT CENTERING (main topic)\n3) DEEPENING (probe deeper)\n4) CLOSING (thank, remind confidentiality)" },
  { s:6, q: "3 Question Types in Interview Guide?", a: "1) DESCRIPTIVE = ask for FACTS\n2) CASUAL = ask for REASONS (why?)\n3) CONSEQUENCE = ask what HAPPENS as a result" },
  { s:6, q: "Interviewer: Do's vs Don'ts?", a: "DO: listen actively, stay objective, show understanding, make summaries, record\nDON'T: fear silence, interrupt, be directive, induce responses, interpret, give opinions" },
  // ===== SESSION 8: Qualitative Analysis (7) =====
  { s:8, q: "Thematic Analysis = ?", a: "Delving through data, IDENTIFYING PATTERNS, systematically CODING, deriving THEMES, creating a NARRATIVE." },
  { s:8, q: "7 Steps of Qualitative Analysis?", a: "1) Familiarize with data\n2) Initial codes\n3) Decide what to code\n4) Merge codes with excerpts (CODIFYING)\n5) Group codes into THEMES\n6) Assess & revise themes\n7) Write results" },
  { s:8, q: "Excerpt vs Code vs Theme?", a: "EXCERPT = word-for-word verbatim\nCODE = word/phrase capturing essence of excerpt\nTHEME = grouping of codes that says something meaningful about the MSP" },
  { s:8, q: "What is Codifying?", a: "GROUPING and CATEGORIZING data by codes to CONSOLIDATE MEANING and explanation. Step 4 of thematic analysis." },
  { s:8, q: "Hierarchy: Excerpt -> Code -> ... -> ?", a: "Transcript -> EXCERPT -> CODE -> SUB-THEME -> THEME -> NARRATIVE" },
  { s:8, q: "Strong vs Weak Themes?", a: "STRONG = most recurring (high frequency of excerpts, many respondents)\nWEAK = less recurring\nDepends on: frequency, # of interviews, length of verbatim" },
  { s:8, q: "Can qualitative findings be generalized?", a: "NO. Sample too small, not statistically representative. BUT they provide INSIGHTS, better UNDERSTANDING, and help DESIGN THE QUESTIONNAIRE for quantitative phase." },
  // ===== SESSION 9: Quantitative Study (12) =====
  { s:9, q: "Quantitative Study = ?", a: "SYSTEMATIC investigation by gathering QUANTIFIABLE data + statistical techniques. It is EXPLANATORY (descriptive) and CONFIRMATORY (causal). Confirms relationships between variables." },
  { s:9, q: "Qualitative vs Quantitative - Key Table?", a: "QUAL: small sample, unstructured, non-statistical, initial understanding\nQUANT: large sample, structured, statistical, recommend final course of action" },
  { s:9, q: "Quantitative Data = ?", a: "Information that can be COUNTED or MEASURED with NUMERICAL value. Either intrinsically quantitative (income) or IMPOSED numeric structure (Likert scale 1-5)." },
  { s:9, q: "Sampling Design Process (3 steps)?", a: "1) DEFINE the population (+ deduce target)\n2) CHOOSE the sampling METHOD\n3) DETERMINE the sample SIZE" },
  { s:9, q: "Population vs Sample?", a: "POPULATION = defined group from which sample is drawn\nSAMPLE = members selected to participate\nProper sampling -> estimate population characteristics" },
  { s:9, q: "When Probability vs Non-probability?", a: "Sampling frame AVAILABLE -> PROBABILITY sampling\nSampling frame NOT available -> NON-PROBABILITY sampling" },
  { s:9, q: "3 Probability Sampling Methods?", a: "1) SIMPLE RANDOM = equal probability for each member\n2) STRATIFIED RANDOM = divide into subgroups (strata), random from each\n3) CLUSTER = identify geographic clusters, sample from those" },
  { s:9, q: "4 Non-probability Sampling Methods?", a: "1) CONVENIENCE = haphazard\n2) PURPOSIVE = researcher's judgment\n3) SNOWBALL = participants recruit others\n4) QUOTA = sample reflects population subgroup composition" },
  { s:9, q: "Quota Sampling?", a: "Most used non-probability method in marketing. Sample MIRRORS POPULATION STRUCTURE on key criteria (age, gender...). Reduces lack of representativeness." },
  { s:9, q: "Single vs Cross Quota?", a: "SINGLE = 1 criterion (e.g., gender)\nCROSS = 2+ criteria crossed (e.g., gender x age)\nToo many criteria (>2-3) = hard to find respondents" },
  { s:9, q: "Sample Size Formula?", a: "n = t²pq / e²\nt=1.96 (95% confidence), p=q=0.5\nSimplified: n = 1/e²\ne=4% -> n=600 | e=2% -> n=2401" },
  { s:9, q: "Margin of Error & Sample Size Rule?", a: "To HALVE the margin of error: QUADRUPLE the sample size.\ne/2 -> n x 4\nHuge consequences on COST and TIME." }
];

