const quizQuestions = [
  // SESSION 1 (3)
  { s:1, q: "What is the role of a market study?", options: ["Only to collect data for competitors", "Assessing info needs, providing relevant info, and helping management make decisions", "Only to create advertising campaigns", "To replace management decision-making"], correct: 1, explanation: "A market study has 3 roles: assessing information needs, providing relevant information, and helping management make informed decisions. (Session 1)" },
  { s:1, q: "Which of the following is NOT part of the definition of consumer behaviour?", options: ["Select and purchase products", "Dispose of products or experiences", "Setting the price of products", "Satisfying needs and desires"], correct: 2, explanation: "Consumer behaviour involves selecting, purchasing, using, and disposing of products to satisfy needs. Setting prices is a marketing decision, not consumer behaviour. (Session 1)" },
  { s:1, q: "A market study is described as:", options: ["A subjective and creative process", "The systematic and objective identification, collection, analysis and use of information", "A simple customer satisfaction survey", "An advertising campaign evaluation"], correct: 1, explanation: "A market study is the systematic and objective identification, collection, analysis, dissemination, and use of information for decision making. (Session 1)" },
  // SESSION 2 (6)
  { s:2, q: "What is the correct definition of 'behaviour' in consumer studies?", options: ["A consumer's overall evaluation of a product", "The cognitive information a consumer holds about an object", "An observed and factual action toward an object", "The process of interpreting sensory information"], correct: 2, explanation: "Behaviour is observed and factual - it is what a consumer actually does. (Session 2)" },
  { s:2, q: "In the consumer behaviour model, what are the two components of the 'Consumer's Black Box'?", options: ["Marketing stimuli and other stimuli", "Consumer characteristics and decision process", "Attitudes and purchase behaviour", "Perception and motivation"], correct: 1, explanation: "The black box contains consumer characteristics and the decision process. (Session 2)" },
  { s:2, q: "The 3 components of attitude (ABC model) are:", options: ["Awareness, Behaviour, Consumption", "Cognition, Affect, Intention to act (Conation)", "Analysis, Belief, Choice", "Cost, Availability, Brand"], correct: 1, explanation: "The ABC model: Cognition (what you know), Affect (what you feel), Conation/Intention to act (what you intend to do). (Session 2)" },
  { s:2, q: "In classical conditioning, attitudes are formed by:", options: ["Rewards and punishments", "Pairing a neutral stimulus with a stimulus that naturally elicits a response", "Direct personal interaction with the product", "Reading product reviews online"], correct: 1, explanation: "Classical conditioning pairs a neutral stimulus with one that naturally elicits a response, until the neutral stimulus alone triggers the response. (Session 2)" },
  { s:2, q: "Beliefs are:", options: ["Easy to change with a single advertisement", "Resistant to change and can be positive, neutral, or negative", "Always factually correct", "The same as attitudes"], correct: 1, explanation: "Beliefs are cognitive information, resistant to change, and can be positive, neutral, or negative. They are not the same as attitudes. (Session 2)" },
  { s:2, q: "Consumer personal characteristics include:", options: ["Age, lifestyle, personality", "Only income and education", "Only culture and social class", "Marketing stimuli"], correct: 0, explanation: "Personal characteristics include age, lifestyle, and personality. Income/education are also personal but the most complete answer includes age, lifestyle, personality. (Session 2)" },
  // SESSION 3 (8)
  { s:3, q: "What is 'perception' according to the course?", options: ["The immediate response of sensory receptors to stimuli", "The process by which sensory information is selected, organized, and interpreted", "A consumer's overall feeling about a product", "The act of purchasing a product"], correct: 1, explanation: "Perception is the process of selecting, organizing, and interpreting sensory info. Option a) is the definition of 'sensation.' (Session 3)" },
  { s:3, q: "What is the correct order of the perceptual process (Solomon, 2018)?", options: ["Attention > Exposure > Interpretation > Sensory stimuli", "Sensory stimuli > Sensory receptors > Exposure > Attention > Interpretation", "Interpretation > Attention > Exposure > Sensory receptors", "Sensory receptors > Motivation > Attention > Behaviour"], correct: 1, explanation: "Stimuli > Receptors > Exposure > Attention > Interpretation. (Session 3)" },
  { s:3, q: "The absolute threshold is:", options: ["The ability to detect differences between two stimuli", "The minimum amount of stimulation detected on a sensory channel", "The maximum amount of sensory input a person can handle", "The point where subliminal messages become conscious"], correct: 1, explanation: "Absolute threshold is the minimum amount of stimulation that can be detected on a sensory channel. The differential threshold (JND) detects differences. (Session 3)" },
  { s:3, q: "Subliminal perception refers to:", options: ["Stimuli that are very loud and obvious", "Stimuli below the level of conscious awareness that may still influence behaviour", "A marketing strategy using bright colors", "Perception through taste only"], correct: 1, explanation: "Subliminal perception: stimuli fall below the absolute threshold, so the consumer is not consciously aware, but they may still influence behaviour. (Session 3)" },
  { s:3, q: "Which is a limitation of Maslow's hierarchy of needs?", options: ["It has too few levels", "The order of needs is always strictly followed by all individuals", "It is culture-specific and the hierarchy may not apply universally", "It only applies to children"], correct: 2, explanation: "Maslow's hierarchy is criticized for being culture-specific. The strict order may not apply universally - some people may prioritize esteem over belongingness. (Session 3)" },
  { s:3, q: "In an approach-avoidance motivational conflict, a consumer:", options: ["Must choose between two equally desirable options", "Wants a product but it also has negative aspects", "Must choose between two equally undesirable options", "Has no conflict at all"], correct: 1, explanation: "Approach-avoidance: the product has both positive and negative qualities. E.g., wanting a dessert (approach) but worrying about calories (avoidance). (Session 3)" },
  { s:3, q: "The difference between moods and emotions is:", options: ["There is no difference", "Moods are intense and specific; emotions are mild and diffuse", "Moods are mild and diffuse; emotions are intense and specific with a clear cause", "Moods last only seconds while emotions last days"], correct: 2, explanation: "Moods: mild, diffuse, no clear cause, last longer. Emotions: intense, specific, clearly identified cause, short-lived. (Session 3)" },
  { s:3, q: "'Brand image' and 'perceived quality' are examples of:", options: ["Functional attributes", "Symbolic attributes", "Primary data", "Sampling methods"], correct: 1, explanation: "Brand image and perceived quality are symbolic (intangible) attributes. Functional attributes are tangible like price, weight, taste. (Session 3)" },
  // SESSION 4 (5)
  { s:4, q: "The Management Decision Problem (MDP) asks:", options: ["What information is needed and how to obtain it", "What the decision maker needs to do", "How to analyze the data collected", "Who should conduct the study"], correct: 1, explanation: "The MDP asks what the decision maker needs to do (action-oriented). The MSP asks what information is needed (research-oriented). (Session 4)" },
  { s:4, q: "A 'brief' in the market study process comes from:", options: ["The research institute", "The government", "The client", "The consumers"], correct: 2, explanation: "The brief is from the client. The proposal is from the supplier/research institute. (Session 4)" },
  { s:4, q: "A descriptive study is used to:", options: ["Provide insights and initial understanding", "Describe market characteristics, estimate percentages, and determine triggers", "Test only cause-and-effect relationships", "Replace the need for a qualitative study"], correct: 1, explanation: "Descriptive study = describe market characteristics (e.g., user profiles, percentages exhibiting a behaviour, determining triggers). It is a type of conclusive study. (Session 4)" },
  { s:4, q: "A causal study aims to:", options: ["Describe the characteristics of respondents", "Obtain evidence regarding cause-and-effect relationships between variables", "Provide insights and understanding only", "Collect secondary data"], correct: 1, explanation: "Causal study = obtain evidence regarding cause-and-effect (causal) relationships. E.g., does X (cause) influence Y (effect)? (Session 4)" },
  { s:4, q: "In the Starbucks case, which study design is needed to identify the triggers that impact attitude and behaviour?", options: ["Exploratory study only", "Descriptive study only", "Causal/confirmatory study (quantitative via survey)", "No study is needed"], correct: 2, explanation: "Identifying triggers that impact attitude and behaviour requires a causal/confirmatory study using a quantitative survey. (Session 4)" },
  // SESSION 5 (4)
  { s:5, q: "Secondary data is:", options: ["Data collected specifically for the current study", "Data collected for some other purpose than the problem at hand", "Data that is always unreliable", "Data from depth interviews"], correct: 1, explanation: "Secondary data was collected for a different purpose. It is existing data and a prerequisite to primary data collection. (Session 5)" },
  { s:5, q: "Which of the following is NOT a characteristic of secondary data compared to primary data?", options: ["Relatively low cost", "Short collection time", "Very involved collection process", "Rapid and easy collection"], correct: 2, explanation: "'Very involved' describes primary data, not secondary data. Secondary data is rapid, easy, low cost, short time. (Session 5)" },
  { s:5, q: "Which is NOT a use of secondary data?", options: ["Identify and better define the problem", "Interpret primary data more insightfully", "Replace all need for primary data collection", "Formulate an appropriate research design"], correct: 2, explanation: "Secondary data helps identify/define problems, develop approaches, formulate designs, and interpret primary data - but it does NOT replace primary data. (Session 5)" },
  { s:5, q: "Internal secondary data includes:", options: ["Government census data", "Professional press articles", "Client database, CRM/ERP, internal reports", "Syndicated services from external providers"], correct: 2, explanation: "Internal data = within the organization (client database, CRM/ERP, internal reports, previous studies). The others are external sources. (Session 5)" },
  // SESSION 6 (6)
  { s:6, q: "A qualitative study focuses on:", options: ["Numerical data and statistical tests", "Words, concepts, ideas, and opinions", "Large, representative samples", "Confirming hypotheses"], correct: 1, explanation: "Qualitative study focuses on words, concepts, ideas, and opinions. It is non-numerical. (Session 6)" },
  { s:6, q: "The 'saturation effect' in qualitative research means:", options: ["The interviewer is too tired to continue", "You stop finding new insights as you interview more participants", "The sample size has reached 100 respondents", "All respondents give the same demographic profile"], correct: 1, explanation: "Saturation = no new insights, ideas, or patterns emerge. This signals the end of interviews. (Session 6)" },
  { s:6, q: "In a semi-structured interview, the interviewer:", options: ["Follows a strict order of pre-determined questions", "Does not impose a specific sequence and can ask follow-up questions", "Only listens and never asks questions", "Uses a questionnaire with closed-ended questions"], correct: 1, explanation: "Semi-structured: topics/questions are set, but no imposed sequence. Free to ask additional questions. (Session 6)" },
  { s:6, q: "The interview guide is structured in:", options: ["2 phases: introduction and conclusion", "4 phases: introductory, subject centering, deepening, closing", "6 phases matching the market study process", "No specific structure is needed"], correct: 1, explanation: "The interview guide has 4 phases: introductory (build trust), subject centering, deepening, and closing (thank respondent). (Session 6)" },
  { s:6, q: "Which type of question asks for reasons behind a behaviour or opinion?", options: ["Descriptive question", "Casual question", "Consequence question", "Closed-ended question"], correct: 1, explanation: "Casual questions ask for reasons why a behaviour/opinion exists. Descriptive questions ask for facts. Consequence questions ask what happens as a result. (Session 6)" },
  { s:6, q: "During an interview, the interviewer should NOT:", options: ["Listen actively and stay objective", "Fear silence and interrupt the interviewee", "Show understanding without interpretation", "Record the interview and take notes"], correct: 1, explanation: "The interviewer should NOT fear silence, interrupt, be directive, induce responses, interpret, or give opinions/judgments. (Session 6)" },
  // SESSION 8 (5)
  { s:8, q: "In thematic analysis, a 'code' is:", options: ["A full paragraph from the transcript", "A word or short phrase that captures the essence of an excerpt", "The name of a respondent", "A statistical formula"], correct: 1, explanation: "A code is a word or short phrase that symbolically assigns a summative, essence-capturing attribute to an excerpt. (Session 8)" },
  { s:8, q: "Which is the correct hierarchy in thematic analysis?", options: ["Theme > Code > Excerpt > Narrative", "Narrative > Theme > Excerpt > Code", "Excerpt > Code > Theme > Narrative", "Code > Excerpt > Narrative > Theme"], correct: 2, explanation: "Transcript > Excerpts > Codes > Themes > Narrative. (Session 8)" },
  { s:8, q: "'Codifying' in thematic analysis means:", options: ["Recording the interviews", "Grouping and categorizing data by codes to consolidate meaning", "Writing the final report", "Selecting participants for interviews"], correct: 1, explanation: "Codifying = grouping and categorizing data by codes to consolidate meaning and explanation. (Session 8)" },
  { s:8, q: "Step 6 of qualitative analysis (assess and revise themes) requires:", options: ["Deleting all themes and starting over", "Checking relevance, ensuring enough data per theme, merging similar themes", "Only adding more themes", "Sending themes to respondents for validation"], correct: 1, explanation: "Step 6: evaluate relevance, ensure enough data per theme, themes must be mutually exclusive. Merge similar ones, delete non-contributing ones. Iterative process. (Session 8)" },
  { s:8, q: "Strong themes depend on:", options: ["The researcher's personal opinion only", "Frequency of excerpts, number of interviews addressing the code, and length of verbatim", "The number of pages in the transcript", "Whether the theme has a catchy name"], correct: 1, explanation: "Strong themes = most recurring content based on frequency of excerpts, number of respondents addressing the idea, and length of verbatim. (Session 8)" },
  // SESSION 9 (8)
  { s:9, q: "Quota sampling is a type of:", options: ["Probability sampling", "Non-probability sampling", "Cluster sampling", "Stratified sampling"], correct: 1, explanation: "Quota sampling is a non-probability sampling method where the sample reflects the numerical composition of subgroups. (Session 9)" },
  { s:9, q: "The main difference between a quantitative and qualitative study outcome is:", options: ["Qualitative recommends a final course of action, quantitative develops initial understanding", "Qualitative develops initial understanding, quantitative recommends a final course of action", "Both aim to develop initial understanding", "Both recommend a final course of action"], correct: 1, explanation: "Qualitative = develop initial understanding. Quantitative = recommend a final course of action. (Session 9)" },
  { s:9, q: "When should you use probability sampling?", options: ["When you have no sampling frame available", "When a sampling frame representing the target population is available and accessible", "When the study is qualitative", "When the budget is very limited"], correct: 1, explanation: "Probability sampling is used when a sampling frame (list of the target population) is available and accessible. (Session 9)" },
  { s:9, q: "The difference between single quota and cross quota sampling is:", options: ["There is no difference", "Single quota uses one criterion; cross quota crosses two or more criteria", "Single quota is probability sampling; cross quota is not", "Cross quota uses only one criterion"], correct: 1, explanation: "Single quota: one criterion (e.g., gender). Cross quota: two or more crossed criteria (e.g., gender x age). Too many (>2-3) makes it difficult. (Session 9)" },
  { s:9, q: "If you want to halve the margin of error (e.g., from 4% to 2%), you need to:", options: ["Double the sample size", "Quadruple the sample size", "Keep the same sample size", "Halve the sample size"], correct: 1, explanation: "To double precision (halve e), you must quadruple the sample size: e/2 -> n x 4. E.g., e=4% n=600 vs e=2% n=2401. (Session 9)" },
  { s:9, q: "A confidence interval is:", options: ["The exact population value", "An interval of values within which there is a given level of confidence the population value lies", "The margin of error only", "The sample size formula"], correct: 1, explanation: "A confidence interval is an interval of values within which there is a given level of confidence that the population value lies. (Session 9)" },
  { s:9, q: "An advantage of quota sampling over other non-probability methods is:", options: ["It is a probability sampling technique", "It reduces the drawback of lack of representativeness by matching population structure", "It requires no knowledge of the population structure", "It is always free of bias"], correct: 1, explanation: "Quota sampling reduces the drawbacks of non-probability sampling (lack of representativeness) by ensuring the sample mirrors the population structure on key criteria. (Session 9)" },
  { s:9, q: "The population in a market study is:", options: ["Only the people who respond to the survey", "The defined group of individuals from which a sample is drawn", "Always the entire country's population", "The same as the sample"], correct: 1, explanation: "The population is the defined group of individuals from which a sample is drawn. The sample is a subset selected to participate. (Session 9)" },
  // ADDITIONAL HIGH-YIELD QUESTIONS
  { s:2, q: "In operant (instrumental) conditioning, attitudes are shaped by:", options: ["Pairing a neutral stimulus with an unconditioned stimulus", "Rewards and punishments following a behaviour", "Personal direct experience with the product", "Subliminal messages"], correct: 1, explanation: "Operant/instrumental conditioning: attitudes are formed through rewards (positive reinforcement) and punishments. Classical conditioning uses pairing of stimuli. (Session 2)" },
  { s:3, q: "Murray's psychogenic needs include categories such as:", options: ["Physiological, safety, and love needs", "Ambition, materialism, power, affection, information, and snobbery", "Only achievement and affiliation needs", "The 5 levels of Maslow's hierarchy"], correct: 1, explanation: "Murray identified 6 categories of psychogenic needs: ambition, materialism, power, affection, information, and snobbery. These differ from Maslow's hierarchy. (Session 3)" },
  { s:4, q: "The first stage of the market study process is:", options: ["Determine the study design", "Data collection and sampling", "Formulate the problem (MDP + MSP)", "Report preparation and delivery"], correct: 2, explanation: "Stage 1 is formulating the problem, which includes defining the MDP (Management Decision Problem) and MSP (Marketing Study Problem). (Session 4)" },
  { s:6, q: "In qualitative research, sampling techniques include:", options: ["Simple random, stratified, and cluster sampling", "Convenience, purposive, and snowball sampling", "Quota sampling only", "Cross-quota and single-quota sampling"], correct: 1, explanation: "Qualitative research uses convenience, purposive, and snowball sampling. Probability methods (simple random, stratified, cluster) require a sampling frame. Quota sampling is for quantitative studies. (Session 6)" },
  { s:9, q: "For a non-probability sampling technique at national scope (general public), the recommended sample size is:", options: ["50 to 100 respondents", "300 to 600 respondents", "1000 to 2000 respondents", "Over 5000 respondents"], correct: 2, explanation: "For non-probability sampling, general public at national scope: n = 1000 to 2000. At city scope: n = 300 to 600. (Session 9)" }
];
